# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        exclude: ".*\\.ipynb$"
      # Run the formatter
      - id: ruff-format
        exclude: ".*\\.ipynb$"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.15.0
    hooks:
      - id: eslint
        args: [--fix]
        files: \.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@9.15.0
          - eslint-config-prettier@9.1.0
