name: "Build and Test"

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Git LFS Pull
        run: git lfs pull
      - name: Build wheel in container
        run: |
          docker build -f docker/Dockerfile -t aiconfigurator:build --target build .
      - name: Run tests in container
        run: |
          docker build -f docker/Dockerfile -t aiconfigurator:test --target test .
          docker run --name aic aiconfigurator:test \
            pytest \
            tests/cli/e2e_validation/test_e2e_sweep.py::TestE2ESweep::test_e2e_configuration_sweep[MODEL_QWEN3_32B__SYSTEM_h200_sxm__GPU_32__ISL_4000__OSL_1000__PREFIX_0__TTFT_5000__TPOT_10__BACKEND_trtllm] \
            tests/cli/e2e_validation/test_e2e_sweep.py::TestE2ESweep::test_e2e_configuration_sweep[MODEL_DEEPSEEK_V3__SYSTEM_h200_sxm__GPU_32__ISL_4000__OSL_1000__PREFIX_0__TTFT_5000__TPOT_100__BACKEND_trtllm] \
            tests/cli/e2e_validation/test_e2e_sweep.py::TestE2ESweep::test_e2e_configuration_sweep[MODEL_QWEN3_32B__SYSTEM_h200_sxm__GPU_32__ISL_4000__OSL_1000__PREFIX_0__TTFT_5000__TPOT_10__BACKEND_sglang] \
            tests/cli/e2e_validation/test_e2e_sweep.py::TestE2ESweep::test_e2e_configuration_sweep[MODEL_DEEPSEEK_V3__SYSTEM_h200_sxm__GPU_32__ISL_4000__OSL_1000__PREFIX_0__TTFT_5000__TPOT_100__BACKEND_sglang] \
            tests/cli/e2e_validation/test_e2e_sweep.py::TestE2ESweep::test_e2e_configuration_sweep[MODEL_QWEN3_32B__SYSTEM_h200_sxm__GPU_32__ISL_4000__OSL_1000__PREFIX_0__TTFT_5000__TPOT_10__BACKEND_vllm] \
            tests/cli/workflow \
            tests/sdk \
            tests/cli/e2e_validation/test_request_latency.py \
            tests/cli/e2e_validation/test_exps.py \
            -v --tb=short --maxfail=1 --timeout=600 \
            -n 4 \
            --md-report --md-report-verbose=1 --md-report-flavor gfm --md-report-output test_report.md
      - name: Copy test report from test Container
        if: always()
        run: |
            docker cp aic:/workspace/test_report.md ./test_report.md
      - name: Render the report to the PR when tests fail
        uses: marocchino/sticky-pull-request-comment@v2
        if: failure()
        with:
          header: test-report
          recreate: true
          path: test_report.md